//get all persons
GET http://localhost:3001/api/persons
###
//get specific person by id
GET http://localhost:3001/api/persons/4
###
//get specific person by id
DELETE  http://localhost:3001/api/persons/3
###
//post person
###
POST http://localhost:3001/api/persons

{
    "name": "Xiaohu Shu",
    "number": "40-329-5962"
}

//get the info of the person count in phonebooks
GET http://localhost:3001/info